version: '3'
services:
    php:
        # image: 'php:7.2-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
          - './app:/var/www/html'
        network_mode: host
#        depends_on:
#            - mariadb
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:80'
            - '443:443'
        #links:
        #    - 'php'
        depends_on: 
          - php
        network_mode: host
        volumes:
            - './app:/var/www/html'
            - getssl_data:/mnt/letsencrypt
            - nginx_data:/mnt/nginx
            - '/var/lib/docker/volumes/nginx_data/_data/conf.d:etc/nginx/conf.d'
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        restart: unless-stopped
#    mariadb:
#        image: mariadb:10.3.9
#        container_name: ${APP_NAME:?err}-mariadb
#        restart: 'on-failure'
#        environment:
#            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
#        volumes:
#            - ${PWD}
volumes:
  getssl_data:
    external: true
  nginx_data:
    external: true
